### ISSUE TITLE
About early stopping during training

### ISSUE THREAD

**Issue by Shimjoonkyo** [SunnyHaze/IML-ViT#15]
Hello, i have a question about training settings in Implementation Details, which say
"Evaluate the performance on the F1 score for CASIAv1, and stop training when there is no improvement for 15 epochs."

Is it right that the you choose the best model based on the TEST dataset results (CASIAv1) ?

**Comment by SunnyHaze** [comment]
Thanks for your attention!

Yes. We select the best model from the best pixel-level F1 result obtained from CASIAv1.

**Comment by SunnyHaze** [comment]
Since we haven't heard back from the original poster for some time, I'll close this issue. Please feel free to reopen it if you need to. Thanks!
