### ISSUE TITLE
about Columbia dataset 

### ISSUE THREAD

**Issue by Linql7** [SunnyHaze/IML-ViT#18]
作者您好，在进行评估时，发现columbia 数据集 个别图片的分辨率大于1024，如canonxt_kodakdcs330_sub_28.tif 的大小为 1152*768 ，对于此类图片，需要如何处理呢，与NIST数据集一样吗，即resize到1024*1024？

**Comment by SunnyHaze** [comment]
对的，从尽可能不破坏篡改痕迹的目标出发，只将这些个别图片resize到1024即可。

**Comment by SunnyHaze** [comment]
哦，我补充一点，我们只是在不改变图像本身的长宽比的前提下，将图片的长边resize到1024。这个可能和你的描述有一点点出入，包括NIST16我们也是这么处理的。

**Comment by Linql7** [comment]
> 哦，我补充一点，我们只是在不改变图像本身的长宽比的前提下，将图片的长边resize到1024。这个可能和你的描述有一点点出入，包括NIST16我们也是这么处理的。

我已理解，不改变图片原有纵横比，将长边resize到1024。

**Comment by Linql7** [comment]
> 哦，我补充一点，我们只是在不改变图像本身的长宽比的前提下，将图片的长边resize到1024。这个可能和你的描述有一点点出入，包括NIST16我们也是这么处理的。

不好意思，又来麻烦您了，我复现的效果始终比不上文章中报告的数据，使用Bathsize 1 ，lr等参数也都一致，训练过程中，每四轮test一轮，对于评估，我调用的是test_one_epoch，评估数据集nist也按照文中方法。目前得到的数据是，在CASIA上150epoch后，几乎能达到0.70的F1，但是在其余的NIST数据集，columbia上 coverage 上达不到文中报告的结果。 我现在不清楚是我评估的数据集处理有问题，还是评估的代码有问题，还是某些超参设置有问题（超参全部按照readme中设置），您能够提供您自用的NIST数据集或评估代码吗？

**Comment by SunnyHaze** [comment]
调参受到很多关键参数影响，比如根据显卡数量和accumulate batchsize不同，会影响等效batchsize，我们目前的实验发现这对于结果影响较大，我们会在后续的论文会对此进行讨论，敬请期待。

**Comment by SunnyHaze** [comment]
评估代码本身就是release出来的test_one_epoch。目前结果有差距，应该是调参的影响会比较大。

**Comment by Linql7** [comment]
> 评估代码本身就是release出来的test_one_epoch。目前结果有差距，应该是调参的影响会比较大。

好的，那应该是超参的影响
