### ISSUE TITLE
Poor visualization about reproducible results by Demo.ipynb and strange F1 scores

### ISSUE THREAD

**Issue by hcztxdy** [SunnyHaze/IML-ViT#20]
The reproduced visualization is quite different from the presentation.

![QQ截图20240627145524](https://github.com/SunnyHaze/IML-ViT/assets/149035050/f9c49329-4d9c-4b3b-b818-5d187fd8e1d8)

And the F1 score is a bit strange, much higher than the essay

![QQ截图20240627145507](https://github.com/SunnyHaze/IML-ViT/assets/149035050/65a95e75-2919-4dee-a85e-2f37c7a79ff0)

![QQ截图20240627150006](https://github.com/SunnyHaze/IML-ViT/assets/149035050/972e909a-c463-4590-80f6-4a0996fe9148)

**Comment by SunnyHaze** [comment]
Hi!
Thanks for your attention to our work.

Please refer to a closed issue to solve your visualization problem: #17. I have provided an English solution here: https://github.com/SunnyHaze/IML-ViT/issues/17#issuecomment-2076553542


From the information you have provided, it is difficult to determine the second issue. I suggest checking the generalization performance on other datasets. If the problem persists, consider using a single GPU and a single batch size to obtain prediction results accurately.


If you have further question, please feel free to reach out.

**Comment by hcztxdy** [comment]
Thank you very much, the first problem has been solved, and the second problem I try the method you provided.

**Comment by SunnyHaze** [comment]
That's great!

For second problem, I believe it is likely an overfitting issue (validated by generalization performance on other datasets. you can try using other Norm to solve this issue) or an unexpected problem during multi-GPU reduction (resolved by using a single GPU and a batch size of 1). 

In our latest work [IMDL-BenCo](https://github.com/scu-zjz/IMDLBenCo), we have addressed the multi-GPU reduction issue, ensuring accurate results even with multiple GPUs and large batch sizes. However, we are still hard working on the documentation and releasing latest features, so please stay tuned for updates.

**Comment by hcztxdy** [comment]
Ok, thanks for the answer.
