### ISSUE TITLE
模型训练不收敛

### ISSUE THREAD

**Issue by wennyHou** [SunnyHaze/IML-ViT#22]
我在自己合成的一个小数据集上做训练，训练了200个epoch，模型一直不收敛。用最后一个epoch的checkpoint在训练数据上做了一下推理，得到的可视化结果是这样的：
![mask](https://github.com/user-attachments/assets/5ad9f96e-6429-4261-971c-1af649748105)
请问有人遇到过这个问题吗?是不是我哪里弄错了

**Comment by SunnyHaze** [comment]
你好，感谢对我们工作的关注！请问是用Demo.ipynb做推理的么？如果是的话请参考 #17 尝试解决，如果没解决请feel free进一步讨论

**Comment by wennyHou** [comment]
> 你好，感谢对我们工作的关注！请问是用Demo.ipynb做推理的么？如果是的话请参考 #17 尝试解决，如果没解决请feel free进一步讨论

感谢回复！可视化结果异常的问题根据您的回复已经解决了

**Comment by wennyHou** [comment]
模型不收敛的问题是由于我使用了BN且batch size设置为2，batch size调整为1之后，就开始收敛了
