### ISSUE TITLE
关于数据集 NIST16 and Defactor-12k

### ISSUE THREAD

**Issue by Makabaka613** [SunnyHaze/IML-ViT#25]
您好！我目前正在从事与图像篡改检测相关的研究。在阅读了您的论文后，我对您所使用的数据集非常感兴趣。我相信这些数据对于我当前的研究将会非常有帮助。我没有找到NIST16 and Defactor-12k数据集的下载链接。因此，我希望能够获得您在研究中使用的NIST16 and Defactor-12k数据集。若可以，烦请告知获取数据集的方法或相关的下载链接。我将会严格遵守您的数据使用规定，仅将其用于学术研究，并在发表的研究成果中对数据集来源进行适当的引用和致谢。非常感谢您的时间和帮助，期待您的回复。

**Comment by SunnyHaze** [comment]
您好，感谢您对我们工作的关注！

NIST16这个数据集需要在NIST(National Institute of Standards and Technology，美国国家标准与技术研究所)官网注册后，获得许可才能进行下载。
- https://mfc.nist.gov/
- https://mfc.nist.gov/participant

理论上在一通操作后进入此网址https://mig.nist.gov/MFC/PubData/Resources.html 下载上方的数据集，也就是一般常说的NIST16（更新的20的一般需要license）：

![image](https://github.com/user-attachments/assets/d4e29708-86b6-419c-a1b7-fcf6755f7d4f)



Defacto请在这个网页和官方取得许可后下载：https://defactodataset.github.io/


祝好！

**Comment by Makabaka613** [comment]
> 您好，感谢您对我们工作的关注！
> 
> NIST16这个数据集需要在NIST(National Institute of Standards and Technology，美国国家标准与技术研究所)官网注册后，获得许可才能进行下载。
> 
> * https://mfc.nist.gov/
> * https://mfc.nist.gov/participant
> 
> 理论上在一通操作后进入此网址https://mig.nist.gov/MFC/PubData/Resources.html 下载上方的数据集，也就是一般常说的NIST16（更新的20的一般需要license）：
> 
> ![image](https://private-user-images.githubusercontent.com/62173481/355298179-d4e29708-86b6-419c-a1b7-fcf6755f7d4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MjIzNDMsIm5iZiI6MTcyMjkyMjA0MywicGF0aCI6Ii82MjE3MzQ4MS8zNTUyOTgxNzktZDRlMjk3MDgtODZiNi00MTljLWExYjctZmNmNjc1NWY3ZDRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDA1MjcyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlZTM3NzlmMDRlOGUyNjE0Y2Q2M2U0MWYzZjA2NTcyZjhiNDgwN2M0NDU1YTkwM2QxOTAyNGU3MzQyOTg3NzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZzZQiKxVMbOZi0W7OkyS6aoQ76tbLIP9UIn5fRAk_GA)
> 
> Defacto请在这个网页和官方取得许可后下载：https://defactodataset.github.io/
> 
> 祝好！

谢谢啦~
