### ISSUE TITLE
自动半精度从哪里修改

### ISSUE THREAD

**Issue by changchaoqun** [SunnyHaze/IML-ViT#27]
作者你好，请问amp在哪个脚本里修改，具体位置是哪

**Comment by SunnyHaze** [comment]
你好，感谢你对我们工作的关注。

自动半精度来自这里：

https://github.com/SunnyHaze/IML-ViT/blob/ae270c7f48f86ba06b308c8151d870e0a5a9b05c/engine_train.py#L47

**Comment by changchaoqun** [comment]
谢谢~，已完成修改
