### ISSUE TITLE
训练和测试的输入

### ISSUE THREAD

**Issue by Makabaka613** [SunnyHaze/IML-ViT#30]
作者您好，我想问下您的代码在训练和测试阶段输入的都是篡改后的图片，没有用到数据集里的原始图片，对嘛

**Comment by SunnyHaze** [comment]
训练阶段可以带真实图片，这个在上一个issue的结尾发的那几个表格中有所体现，你找一下，普遍来说，带了真实图片以后，指标会低一些。但是能减少假阳性率，反正你注意report的时候的一致性就行。

测试阶段则完全不能带真实图片，因为因为真实图片没有true positive，计算f1分数是没有意义的。

**Comment by SunnyHaze** [comment]
![image](https://github.com/user-attachments/assets/13daf2be-a332-449c-89f2-4dd8b65a6e71)
这张图，CASIA-5k是只有篡改图像，CASIA-12k是二者都带。

**Comment by SunnyHaze** [comment]
测试时不能带真图的证明参考以前的回答：https://github.com/SunnyHaze/IML-ViT/issues/4#issuecomment-1863998642

**Comment by Makabaka613** [comment]
好哒，我懂啦，谢谢您，祝好~
