### ISSUE TITLE
关于单独测试代码

### ISSUE THREAD

**Issue by hcztxdy** [SunnyHaze/IML-ViT#31]
请问使用训练好的模型在不同数据集上测试的代码是这个吗https://github.com/SunnyHaze/IMDLBenCo/blob/main/IMDLBenCo/training_scripts/test.py
我调了一段时间代码还是无法运行，请问应该怎么设置才能运行，或者IML-VIT的测试代码不是这个。

**Comment by SunnyHaze** [comment]
你好，感谢对IML-ViT与IMDL-BenCo工作的关注。

您索引的路径是在我个人名下BenCo的开发代码，不是我们最终release的版本。

我今天刚完善了BenCo关于模型复现部分的文档，您可以参考“使用Model_zoo复现SoTA模型”这部分尝试复现，如果有任何疑问可以在这里讨论，我们会第一时间做出回复和必要的修正。


快速上手教程：http://localhost:8080/IMDLBenCo-doc/zh/guide/quickstart/install.html

**Comment by SunnyHaze** [comment]
不好意思上述链接是本地开发的，这份是公开的文档链接：

https://scu-zjz.github.io/IMDLBenCo-doc/zh/guide/quickstart/install.html

**Comment by SunnyHaze** [comment]
如果有其他问题，欢迎讨论！

**Comment by hcztxdy** [comment]
好的，非常感谢！

**Comment by zijieloooooou** [comment]
如果能有一个单独的测试代码确实会方便许多

**Comment by SunnyHaze** [comment]
> 如果能有一个单独的测试代码确实会方便许多

@ZXMMD 是这样，原始的IML-ViT用于实验的测试代码，只能确保单卡单batchsize下的绝对准确，如果使用多卡大batchsize，会因为pytorch在组织distribute的数据集的时候，试图补全or去尾某几个sample，引起指标浮动。

这个问题的具体test case请参考这里：https://github.com/scu-zjz/IMDLBenCo/blob/main/tests/test_drop_last.py

这个问题在IMDL-Benco中被solve了，所以才建议采用Benco。还望理解
