### ISSUE TITLE
关于Train Dataset和Test Dataset的疑问 & 训练Log中括号内外数值的含义

### ISSUE THREAD

**Issue by Sparrowwwwho** [SunnyHaze/IML-ViT#33]
作者您好，大多数的文章都将CASIA V2 按照9:1的train和val划分，但代码中只有Train path和Test path，所以我在一开始的训练中在Test path填入了CASIAV2的路径，训练25轮后对CASIA V1 的F1只有0.01（训练中V2的test结果是0.43），但是改成CASIA V1的路径后F1为0.56。
所以想问下作者，这个test在训练的过程中是起到了验证集的作用还是单纯的在训练过程中进行一个直白的评估呢？

**Comment by SunnyHaze** [comment]
你好，感谢您对我们工作的关注！

由于篡改检测的数据集往往比较小，所以现在很多新的工作不再采用随机划分训练测试集的方式来评估篡改检测模型的性能了。而是通过采用cross-dataset，即在一个大的数据集上训练，另一些小数据集上测试的方式来完成对于模型性能的评估，这样能更加合理，客观地排除数据集过小，分布过近的bias。也正是我们工作与MVSS-Net中使用的方式，

至于test数据集的作用，我们一般用这个数据集评估训练性能，并初步筛选最优Epoch在其他数据集上测试，所以应该是起到了验证集的作用。

**Comment by Sparrowwwwho** [comment]
感谢回答，现在我发现了一个新的问题，作者您提供的训练权重在demo中所得到的F1为0.6506，但在我训练后无论训练多少轮，在demo所得到的F1均低于0.02，在训练时的测试结果似乎也有些问题："test_average_f1": 数值1（数值2），在早期轮数中，数值1小于数值2，如0.102（0.384），到了后期又变成了数值1大于数值2，如0.893（0.605）。

demo的低结果也说明了为什么Test path填入CASIAV2后F1低的原因（即便Test path填入CASIAV1，在demo中的结果也仅为0.015）

**Comment by SunnyHaze** [comment]
如果您使用的是demo.ipynb进行测试，请参考 #17 尝试解决部分问题。

如果还是没有解决，可以进一步讨论。

或者请pull最新的demo.ipynb来尝试解决问题。我在最新的commit里面通过try-catch自动解决可能的歧义：https://github.com/SunnyHaze/IML-ViT/commit/c67cfe7364c32b96e4cb26a684baa8568b46318d

**Comment by SunnyHaze** [comment]
至于“数值1，数值2”的问题，请以括号内的数值为准。

这个是由于pytorch多卡并行reduce，收集合并不同显卡的数据带来的问题，“数值1”是“用于print的显卡，即一般0号显卡当前batch的数值”，它的高低只能反应一个特殊的batch的结果，而括号内的“数值2”是归并后所有显卡的数值，是真正衡量整个数据集性能，需要关注的结果。

请以pytorch多卡并行，reduce为关键字检索相关技术。如果有其他问题，欢迎讨论。

**Comment by Sparrowwwwho** [comment]
已经解决，谢谢作者^^

**Comment by ProgrameThinking** [comment]
作者您好，如果我仅仅采用一张显卡进行训练，“数值1，数值2”也不是相同的数值，请问问题的原因是什么

> 至于“数值1，数值2”的问题，请以括号内的数值为准。
> 
> 这个是由于pytorch多卡并行reduce，收集合并不同显卡的数据带来的问题，“数值1”是“用于print的显卡，即一般0号显卡当前batch的数值”，它的高低只能反应一个特殊的batch的结果，而括号内的“数值2”是归并后所有显卡的数值，是真正衡量整个数据集性能，需要关注的结果。
> 
> 请以pytorch多卡并行，reduce为关键字检索相关技术。如果有其他问题，欢迎讨论。

**Comment by SunnyHaze** [comment]
@ProgrameThinking 感谢您对我们工作的关注！

因为这个归并实际上还参与了“不同Batch”之间的归并，即括号内的数值是当前epoch，累计已经计算过的所有batch过后的数值。而数值1则是0号卡，当前batch的当前数值。

你可以从括号内的数值，在前几个batch过后后逐渐趋于稳定，来看到这样的结论。

如果还有其他问题，欢迎讨论。

**Comment by ProgrameThinking** [comment]
那我是否可以理解成，这是将多个Batch所得到的结果累计后进行最后的“平均”，而第一个数则是当前batch所得到的结果。而这个平均就是您所说的归并过程，而非数学上的平均

**Comment by SunnyHaze** [comment]
实质上这个数值来源于这个logger里面的smoothedValue：
https://github.com/SunnyHaze/IML-ViT/blob/8aa67af93e40e4671e4ac5cc69ae5872210d7249/utils/misc.py#L33

我仔细查了一下代码。。。并不完全是我说的那样。有一些出入。

SmoothValue维护一个长度为20的队列，先进先出，始终只有20个值。

另外维护了所有经过update的值的sum（总和）和count（个数）用于计算全体均值。

可以看到实质上前者是torch.meadian中位数，是该长度20的队列中的中位数
https://github.com/SunnyHaze/IML-ViT/blob/8aa67af93e40e4671e4ac5cc69ae5872210d7249/utils/misc.py#L57-L60

后者则用于计算当前所有被update过的数的平均值
https://github.com/SunnyHaze/IML-ViT/blob/8aa67af93e40e4671e4ac5cc69ae5872210d7249/utils/misc.py#L67-L69

而卡间归并（reduce）则是独立于二者的。它发生在下面这个syncronize函数被调用的时候，：

https://github.com/SunnyHaze/IML-ViT/blob/8aa67af93e40e4671e4ac5cc69ae5872210d7249/utils/misc.py#L44-L55

而实际上这个东西仅发生在一个epoch最后：
https://github.com/SunnyHaze/IML-ViT/blob/8aa67af93e40e4671e4ac5cc69ae5872210d7249/engine_train.py#L87

所以你实际看到的输出，除了最后一行的Summary输出，实质上应该都是第0号卡的smoothValue的对应输出（20中位数or第0号卡的当前均值）

所以我上面说的不够准确，请以本回答为准。

**Comment by ProgrameThinking** [comment]
感谢您的耐心解答🙏
