### ISSUE TITLE
关于测试数据集Defacto dataset的，是否可以直接提供文章中提到的这个数据集？

### ISSUE THREAD

**Issue by maominluck** [SunnyHaze/IML-ViT#34]
作者，你好，非常感谢你的工作；通过阅读论文，了解到你在测试时候使用的这个Defacto 数据集是由MS-COCO数据集中随机选择了6000张未接触过的图像，并将其与Defacto的6000张图像合并，创建Defacto-12k数据集（因为Defacto数据集中没有真实图像作为负例），请问可以直接提供该数据集吗？谢谢

**Comment by SunnyHaze** [comment]
诚然不建议后续文章使用这个数据集比较，因为它的gap与CASIAv2实在太大，大多数篡改都是非常微小的object。

客观来说各个论文中report的0.1左右的F1，只要全预测为白色，也能达到这样的结果，这样的指标实在不具备参考意义，所以真的不建议后续文章使用该数据集，加上IMD-2020可能是个better choice。
