### ISSUE TITLE
关于集成后Benco中训练产生的log.log文件

### ISSUE THREAD

**Issue by Jytylyqyrs** [SunnyHaze/IML-ViT#38]
![1](https://github.com/user-attachments/assets/353dbb33-b67c-4fee-b668-faf084330755)
冒昧的请问，调用benco库训练时产生的log.log文件中，pixel-levle F1以及Seg loss的两个值分别指的是什么（两个值，一个带括号一个不带括号）

**Comment by SunnyHaze** [comment]
你好，感谢你对我们仓库的关注！

请问您复现的是IML-ViT还是benco，本仓库是IML-ViT的仓库。

seg_loss应该是PSCC-Net中返回的一个参数。

至于这两个值，括号外的数值是当前batch的数值。括号内的数值是经过PyTorch的多卡归并，即Tensor.reduce()的数值，即在所有GPU同步数据后的当前数值。最终需要report的结果是最后一个step的括号内的数值。

希望能解决你的问题，如果还有其他issue，欢迎进一步讨论。（如果是Benco的Issue尽量还是发到Benco的仓库，谢谢！）

**Comment by SunnyHaze** [comment]
因为长时间没有更新的update，所以关闭本Issue。
