### ISSUE TITLE
您好！想请问一下您的测试集中是否包含了真实图片

### ISSUE THREAD

**Issue by wyx0203** [SunnyHaze/IML-ViT#39]
您好，我最近有幸读到您的文章，在复现结果的时候发现在Columbia数据集做测试时，如果加入真实图片，平均F1就会降到0.4+。我自己的方法也是这样，想请问您所比较的那一篇MVSS-Net也是这样的实验设置嘛，我看他论文里也没有很明确的说是否使用了真实图片。
希望您不吝赐教！

**Comment by SunnyHaze** [comment]
请参考这个的第三点：
https://github.com/SunnyHaze/IML-ViT/issues/4#issuecomment-1863998642

主要是因为真图没法算F1，参见公式（没有TP，所以无意义），所以测试的时候不能引入。

**Comment by wyx0203** [comment]
谢谢谢谢！
