### ISSUE TITLE
关于mvss协议的疑问

### ISSUE THREAD

**Issue by fcm2018** [SunnyHaze/IML-ViT#40]
我想问一下，在论文报告的指标，所有测试数据集是基于同一个epoch的结果还是不同epoch的结果

**Comment by SunnyHaze** [comment]
是同一个epoch下的。

**Comment by fcm2018** [comment]
> 是同一个epoch下的。

感谢回复！

**Comment by SunnyHaze** [comment]
arxiv更新了最新的paper，指标请以此为参考。

**Comment by fcm2018** [comment]
好的，那我想问一下，这个最新报告的指标和之前的指标有什么区别，是epoch不一样，还是有调整某些超参数重新训练。顺便关于边缘监督的权重，代码中给出的是20，我想问一下这样的考量是不是出于边缘和主体掩码之间白色像素点数量比例的差异

**Comment by SunnyHaze** [comment]
来自于调参，主要是accumulate iteration与显卡数量的配合。

关于20，直觉上是因为不仅白色区域总体占比少，而且，本文使用了一些zero padding的策略，导致白色区域就更少了，所以说必要的大权重lambda平衡可以让收敛更稳定。在新的论文中也有实验说明。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年11月28日 06:10 |
| 收件人 | ***@***.***> |
| 抄送至 | Ma, ***@***.***>、State ***@***.***> |
| 主题 | Re: [SunnyHaze/IML-ViT] 关于mvss协议的疑问 (Issue #40) |

好的，那我想问一下，这个最新报告的指标和之前的指标有什么区别，是epoch不一样，还是有调整某些超参数重新训练。顺便关于边缘监督的权重，代码中给出的是20，我想问一下这样的考量是不是出于边缘和主体掩码之间白色像素点数量比例的差异
