### ISSUE TITLE
关于json格式的dataset如何构造的问题

### ISSUE THREAD

**Issue by Stitchsong** [SunnyHaze/IML-ViT#7]
作者您好，十分感谢您的工作和开源。
我对于数据JSON格式那里有一些疑问
<img width="546" alt="Snipaste_2024-01-05_10-31-11" src="https://github.com/SunnyHaze/IML-ViT/assets/48827949/719db0a6-9118-46b0-86a6-080a4de1deef">
这个说明中json格式不是应该来自同一个数据集吗？而不是Gt来自另外的数据集CASIAv2的数据
比如应该是这样：
[
      "/Dataset/CASIAv2/Tp/image1.jpg",
      "/Dataset/CASIAv2/Gt/image1.jpg"
    ],
同时，
[
      "/Dataset/CASIAv1/Tp/image2.jpg",
      "Negative"
    ],
这个里面Tp代表着伪造，下面不应该写着Negative，还是我对您的Negative有着其他的误解？
应该写成这样
[
      "/Dataset/CASIAv1/Au/image2.jpg",
      "Negative"
    ],
    希望能得到您的解答！

**Comment by SunnyHaze** [comment]
您好，感谢你的关注！

这里确实我写readme的时候在下面Authentic那部分只是把上面的copy到下面写的，是一个瑕疵。诚然，如果groundtruth是“Negative”的话，应该对应的是Authentic image。

当然，CASIAv1是没有Authentic image的，我实际训练中会用到的json的节选是这样的，使用了CASIAv2的一张真实图片：
```
...
    [
        "/home/xxxxxx/Datasets/CASIA2.0_corrected/Au/Au_art_00002.jpg",
        "Negative"
    ],
....
```
我会在readme中修改这部分避免歧义。

希望能帮到你，如果有其他问题欢迎提问！

**Comment by SunnyHaze** [comment]
请参考最新的commit：https://github.com/SunnyHaze/IML-ViT/commit/3ffd03db8b95824ce0b67c55ee1628ec106a666
已经对readme进行订正，再次感谢你的issue！

**Comment by Stitchsong** [comment]
感谢，我还有个问题，另外一个格式中并没有文件夹用来放Au数据集，那是不是那个格式中本身就不含有Au的部分？
感谢您的解答！

**Comment by SunnyHaze** [comment]
对的，设计的时候就是这样，如果需要带Authentic image就用这个`json_dataset`。

`mani_dataset` 主要是考虑方便快速的组织数据集，需要的图片只要名字顺序一致，拷贝进去就能用，而且很多IML数据集是没有准备自己的Authentic image的，所以没有留这个接口。我个人经常拿这个来准备evaluation用的dataset，因为evaluation不能有Authentic image。

**Comment by Stitchsong** [comment]
非常感谢，十分期待您的下一篇IML文章

**Comment by SunnyHaze** [comment]
哈哈，共勉朋友！ 🤗
