### ISSUE TITLE
about resolution mismatch in COVERAGE dataset

### ISSUE THREAD

**Issue by shunlibiyela** [SunnyHaze/IML-ViT#9]
您好，请问coverage数据集里的9张图片image和mask的尺寸对不上的问题您是怎么解决的呢？

**Comment by SunnyHaze** [comment]
您好，感谢您的关注！

我们手动修改并调整了一份，你可以邮箱联系我我发给你，后续我有时间可能会单独开一个repo放这几张修改后的图片。

**Comment by SunnyHaze** [comment]
________________________________
From: ***@***.*** ***@***.***> on behalf of shunlibiyela ***@***.***>
Sent: Tuesday, March 5, 2024 2:36:41 AM
To: SunnyHaze/IML-ViT ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [SunnyHaze/IML-ViT] about COVERAGE (Issue #9)


您好，请问coverage数据集里的9张图片image和mask的尺寸对不上的问题您是怎么解决的呢？

**Comment by SunnyHaze** [comment]
目前我们将所有修改过的数据集上传到了这个仓库，方便用于复现IML-ViT与完成后续工作，欢迎star或分享给其他Researcher，感谢！
https://github.com/SunnyHaze/IML-Dataset-Corrections
